from .component_serializers import ComponentSerializer, ComponentMinimalSerializer
from .vehicle_serializers import VehicleSerializer, VehicleMinimalSerializer
from .service_serializers import ServiceRecordSerializer, ServiceRecordListSerializer, ServiceIssueSerializer
from .invoice_serializers import InvoiceSerializer
